_target_: src.model.ClassifierModel

motion_encoder:
  _target_: src.model.ACTORStyleEncoder
  nfeats: ${data.motion_loader.nfeats}
  vae: true
  latent_dim: 256
  ff_size: 1024
  num_layers: 6
  num_heads: 4
  dropout: 0.1
  activation: gelu

hidden_dim: 128
lr: 1e-4
cache: true