_target_: src.model.StartEndSegmentationModel

lr: 1e-4

defaults:
  - motion_encoder: stgcn
  - classifier: mlp
  - label_extractor: transition-based-start-end-without-majority
  - window_positional_encoder: null

classifier: ???
motion_encoder: ???
label_extractor: ???