device: cuda:1

run_dir: ???
window_step: ???

ckpt: best

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 8

examples: true

defaults:
  - vote_manager: score-based
  - data: babel-windowed
  - model: start-end-segmentation
  # - trainer
  - defaults
  - _self_

data:
  preload: false