run_dirs:
  - /home/nadir/tmr-code/outputs/model=start-end-segmentation_pos=none_motion-encoder=tmr_label-extractor=majority-based-start-end-with-majority_pretrained=False_classifier=mlp_window-size=20
  - /home/nadir/tmr-code/outputs/model=start-end-segmentation_pos=none_motion-encoder=stgcn_label-extractor=majority-based-start-end-with-majority_pretrained=False_classifier=mlp_window-size=20

window_step: 1

defaults:
  - vote_manager: score-based
# score-based or class-based

device: cuda:1
qualitative_run_index: 0
num_qualitative_examples: 100
ckpt: best